### PR TITLE
Use the new context macro in the README examples

### PR DESCRIPTION
**Pull request by lovasoa**
This makes the README more digest, in my opinion.

### CODE REVIEW

**Comment by lovasoa** [comment]
Related to #48

**Comment by ISibboI** [comment]
Thank you very much for this pull request. I agree it improves the readability of the README.
Can you do the changes in `src/lib.rs` as well? Because I use the `cargo-sync-readme` subcommand for this crate, that syncs from the `src/lib.rs` to the `README.md`, but sadly not the other way around.

**Comment by lovasoa** [comment]
Hi! I'm sorry, but I don't have the time to do it right now. I gave you the right to edit this PR.

**Comment by ISibboI** [comment]
Thank you very much, I quickly synchronized the files by hand.

**Pull request merged**
