### PR TITLE
Add math::abs function

### PR DESCRIPTION
**Pull request by LinuxHeki**

### CODE REVIEW

**Comment by ISibboI** [comment]
This is a great idea! Could we add it in the way that it returns integers if the input value is integer? Since abs can be defined both on integers and floats.

**Comment by LinuxHeki** [comment]
Sure we can. This would probably require more than just one line of code.

**Comment by LinuxHeki** [comment]
Done! It was easier than I thought

**Comment by ISibboI** [comment]
Great thanks, I can take it from here.

**Comment by ISibboI** [comment]
If you want me to release this now, please just make a comment. Otherwise, I'd release it together with #131.

**Pull request merged**
