### PR TITLE
Add variable nesting and map type

### PR DESCRIPTION
**Pull request by solaeus**
I like this project a lot and the code is very nice so I wanted to try this issue #117. 

This is a rough draft that currently only supports getting values from up to two levels of nesting. I have a fork with a more complete solution but this was an attempt to change as little as possible. Some tests fail due to the new syntax and a new error type.

If there's still interest in this feature I can either try to find a solution in the existing code or use the technique I used in my fork, which was to create a new context type that can be wrapped in a value.

```fish
cargo run --bin evalexpr 'x.y = 1; x.z = 2; x.a.b = 3; x.c.d.e = 8; x'
# ( a = ( b = 3; ); z = 2; y = 1; c = ( d.e = 8; ); )
```

### CODE REVIEW

**Comment by ISibboI** [comment]
Thank you! This looks good so far. I think it would be a nice-to-have feature.

**Comment by Dzordzu** [comment]
Hi. Any progress on this?

**Comment by solaeus** [comment]
I'm no longer using evalexpr but I'll take another look at this issue next week. If this is still the closest that we've gotten to this feature I will try to get it merged.

**Comment by solaeus** [comment]
Sorry this is taking longer than I thought, some other stuff came up but I am working to get this done.

**Comment by Dzordzu** [comment]
Easy. Thanks for you efforts!

**Pull request closed without merging**
